networks:
  dask-cluster-net:
    driver: bridge

volumes:
  prefect-data:

services:
  prefect-server:
    build: .
    container_name: prefect-server
    hostname: prefect-server
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200" # Prefect Dashboard/API
    networks:
      - dask-cluster-net
    volumes:
      - prefect-data:/root/.prefect

  dask-scheduler:
    build: .
    container_name: dask-scheduler
    hostname: dask-scheduler
    command: dask scheduler --host 0.0.0.0
    depends_on:
      - prefect-server
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    ports:
      - "8786:8786" # IPC (comunicación scheduler <-> workers/cliente)
      - "8787:8787" # Dask Dashboard
    networks:
      - dask-cluster-net
    volumes:
      - ./shared-data:/app/shared-data
    cpus: 1.0
    mem_limit: 1g

  dask-worker-1:
    build: .
    container_name: dask-worker-1
    hostname: dask-worker-1
    command: dask worker tcp://dask-scheduler:8786 --nthreads 2 --nworkers 1 --memory-limit 1.5GB --name worker-1
    depends_on:
      - dask-scheduler
    networks:
      - dask-cluster-net
    volumes:
      - ./shared-data:/app/shared-data
    cpus: 2.0
    mem_limit: 1.5g

  dask-worker-2:
    build: .
    container_name: dask-worker-2
    hostname: dask-worker-2
    command: dask worker tcp://dask-scheduler:8786 --nthreads 2 --nworkers 1 --memory-limit 1.5GB --name worker-2
    depends_on:
      - dask-scheduler
    networks:
      - dask-cluster-net
    volumes:
      - ./shared-data:/app/shared-data
    cpus: 2.0
    mem_limit: 1.5g

  dask-worker-3:
    build: .
    container_name: dask-worker-3
    hostname: dask-worker-3
    command: dask worker tcp://dask-scheduler:8786 --nthreads 2 --nworkers 1 --memory-limit 1.5GB --name worker-3
    depends_on:
      - dask-scheduler
    networks:
      - dask-cluster-net
    volumes:
      - ./shared-data:/app/shared-data
    cpus: 2.0
    mem_limit: 1.5g
